version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - payment-service
      - notification-service
      - product-service
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8081:8081"

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8082:8082"

  product-service:
    build:
      context: ./product-service
    ports:
      - "8080:8080"
